name: Drift detection

on:
  workflow_dispatch:

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download AT-drift-detection
        run: |
          # 최신 릴리즈 다운로드
          wget https://github.com/zkfmapf123/AT-drift-detection/releases/latest/download/at-plan-linux-amd64
          chmod +x at-plan-linux-amd64
          sudo mv at-plan-linux-amd64 /usr/local/bin/at-plan
      
      - name: Run Drift Detection
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ATLANTIS_TOKEN: ${{ secrets.ATLANTIS_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          at-plan plan \
            -g $GITHUB_TOKEN \
            -f main \
            -u https://atlantis.dev.leedonggyu.com \
            -t $ATLANTIS_TOKEN \
            -r zkfmapf123/atlantis-fargate \
            -c atlantis.yaml \
            -s $SLACK_BOT_TOKEN \
            -l C05CMUWAHEK
          